// Expensive inference belongs to the backend; final RGB must come from a photo.
export const CUTOUT_CONFIG = {
  USE_HIGH_RES_FINAL_CAPTURE: true,
  USE_POINT_BOX_FINAL_SEGMENTATION: true,
  USE_HAND_NEGATIVE_PROMPT: true,
  USE_SHARPNESS_GATE: true,
  USE_HOVER_SELECTION: true,
  FINAL_CAPTURE_STABILITY_MS: 180,
  CAMERA_READY_TIMEOUT_MS: 4000,
  HAND_REACQUIRE_TIMEOUT_MS: 1200,
  MAX_RECAPTURE_COUNT: 1,
  RECAPTURE_DELAY_MS: 100,
  HOVER_STABILITY_MS: 250,
  HOVER_REQUEST_INTERVAL_MS: 1000,
  CANDIDATE_MAX_AGE_MS: 1500,
  HOVER_MOVE_THRESHOLD: 0.025,
} as const
