export const APP_CONFIG = {
  DEBUG_MODE: true,
  SHOW_DEBUG_CONTROLS: false,
  USE_MOCK_HAND_TRACKING: false,
  USE_MOCK_SEGMENTATION: false,
  VISION_API_BASE_URL: 'http://192.168.67.18:8000',
  CAMERA_FRAME_INTERVAL_MS: 120,
  VISIONKIT_FPS: 24,
  SPATIAL_UI_FPS: 20,
  COPY_ANIMATION_MS: 620,
} as const;
