export const APP_CONFIG = {
  DEBUG_MODE: true,
  USE_MOCK_HAND_TRACKING: false,
  USE_MOCK_SEGMENTATION: true,
  USE_MOCK_PERLER: true,
  CAMERA_FRAME_INTERVAL_MS: 120,
  VISIONKIT_FPS: 30,
  COPY_ANIMATION_MS: 620,
} as const;
